# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.hostname = "vagrantslurm"
  config.vm.provider "libvirt" do |lv|
      lv.memory = 8192
      lv.cpus = 4
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant_playbook.yml"
  end
end
